[package]
name = "todo-app"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio", "macros", "chrono"] }
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["full"] }
 
